analyzer:
  errors:
    deprecated_member_use: ignore
    dead_null_aware_expression: ignore
    unused_local_variable: ignore
    unused_field: ignore
    unused_import: ignore
    included_file_warning: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
